python attack_main.py ^
-model perceiver_classifier ^
-eval classification_crossentropy ^
-in ../data/img_data/perc_224/tench.png ^
-tl 0 ^
-min ^
-b 100 ^
-ps 2 -os 4 ^
-d 0.4 ^
-e 0.05 ^
-r intermediate ^
-m one_fifth ^
-s plus_selection ^
-v 2