python attack_main.py ^
-model xception_classifier ^
-eval classification_crossentropy ^
-in ../data/img_data/tench.png ^
-tl 0 ^
-min ^
-b 1000 ^
-ps 2 -os 20 ^
-d 0.15 ^
-e 0.1 ^
-r intermediate ^
-m individual_sigma ^
-s plus_selection ^
-v 2