python attack_main.py ^
-model xception_classifier ^
-eval crossentropy ^
-in ../data/img_data/testxcept/ ^
-tl 4 ^
-min ^
-b 1000 ^
-ps 4 -os 4 ^
-d 0.9 ^
-e 0.02 ^
-r global_discrete ^
-m one_fifth_alt ^
-s plus_selection ^
-fp 5 ^
-v 2