python attack_main.py ^
-model xception_classifier ^
-eval crossentropy ^
-in ../data/img_data/testperc/ ^
-tl 0 ^
-min ^
-b 10000 ^
-ps 2 -os 4 ^
-d 0.4 ^
-e 0.05 ^
-r intermediate ^
-m one_fifth ^
-s plus_selection ^
-fp 5 ^
-v 2