python attack_main.py ^
-model xception_classifier ^
-eval crossentropy ^
-in ../data/img_data/xcept_299/ ^
-tl 0 ^
-min ^
-b 300 ^
-ps 10 -os 10 ^
-d 0.8 ^
-e 0.02 ^
-r discrete ^
-m individual ^
-s plus_selection ^
-v 2