python attack_main.py ^
-model xception_classifier ^
-eval classification_crossentropy ^
-in ../data/img_data/xcept_299/ ^
-tl 0 ^
-min ^
-b 100 ^
-ps 2 -os 4 ^
-d 1 ^
-e 0.06 ^
-r discrete ^
-m individual ^
-s plus_selection ^
-v 2